image:
  repository: slechev/openwebrxplus-softmbe
  pullPolicy: IfNotPresent
  tag: 1.2.87@sha256:d2464ed8da5f2d41ce7c407f7e748722d912233993c591dea66511043aa8b6c7

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
        env:
          OPENWEBRX_ADMIN_USER: "admin"
          OPENWEBRX_ADMIN_PASSWORD: "changeme"


service:
  main:
    ports:
      main:
        protocol: http
        port: 8073
        targetPort: 8073
